#!/bin/bash

# ==============================================================================
#
#   Slurm Job Submission Script
#
#   Generated by:   Interactive Slurm Script Generator v1.0.1
#   Author:         orincon
#   Generated On:   Fri Nov 14 17:07:14 -05 2025
#
# ==============================================================================


#==============================================================================
# SBATCH DIRECTIVES (generated on Fri Nov 14 17:08:59 -05 2025)
#==============================================================================
#SBATCH --job-name="nn_train_orincon_sbatch"
#SBATCH --partition=accel-2
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=4G
#SBATCH --gres=gpu:1
#SBATCH --time=1-01:00:00
#SBATCH --output=logs/%x_%j.out      # Standard output log (%x = job name, %j = job ID)
#SBATCH --error=logs/%x_%j.err       # Standard error log
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=orincon@eafit.edu.co         # Your email address from user input

#==============================================================================
# SCRIPT BODY
#==============================================================================

echo "================================================="
echo "Starting job $SLURM_JOB_ID on host $(hostname)"
echo "Job name: $SLURM_JOB_NAME"
echo "Partition: $SLURM_JOB_PARTITION"
echo "Number of nodes: $SLURM_NNODES"
echo "Total number of tasks: $SLURM_NTASKS"
echo "================================================="
echo

# --- Environment Setup ---
# Load any necessary modules
module load miniconda3/25.11.1

# Activate a virtual environment
source activate nn-train-env

# --- Application Execution ---
echo "Starting application..."
echo

# Insert code here
# nvidia-smi
python simple_nn_training.py

# echo
# echo "================================================="
# echo "Job finished with exit code $?"
# echo "================================================="
